CREATE TABLE EVENT_IMAGE (
    EVENTID NUMBER CONSTRAINT PK_IMAGE PRIMARY KEY,
    IMAGE BLOB,
    ALT_TEXT VARCHAR2(100),
    CONSTRAINT FK_EIMAGE FOREIGN KEY (EVENTID)
                         REFERENCES EVENT(EVENTID)
);