CREATE TABLE PASSWORD_RESET_TOKEN (
    TOKEN_ID NUMBER CONSTRAINT PK_TOKEN PRIMARY KEY,
    TOKEN VARCHAR2(255) CONSTRAINT UNIQ_TOKEN UNIQUE,
    USERID NUMBER,
    EXPIRE_DATE DATE NOT NULL,
    CONSTRAINT FK_USER_TOKEN FOREIGN KEY (USERID) REFERENCES LOGGEDUSER(USERID)
);